### ISSUE TITLE
an error when installing chaincode on peer node

### ISSUE THREAD

**Issue by lc32781971** [vanitas92/fabric-external-chaincodes#1]
I got an error when installing chaincode on peer node . How should i fix this?

/opt/gopath/src/github.com/hyperledger/chaincode/packaging # peer lifecycle chaincode install marbles-org1.tgz
Error: chaincode install failed with status: 500 - Failed to authorize invocation due to failed ACL check: Failed verifying that proposal's creator satisfies local MSP principal during channelless check policy with policy [Admins]: [The identity is not an admin under this MSP [org1MSP]: The identity does not
contain OU [ADMIN], MSP: [org1MSP]]

**Comment by vanitas92** [comment]
This is the first time i see this error. Seems like the genesis block has not been encoded correctly. Can you try to start from the beginning and see if it happens again?

**Comment by zhangfuli** [comment]
I got an error when installing chaincode on peer node too, but I got this:
```
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
```
So it seems it cannot connect to the Docker endpoint. But I cannot find how to fix this.
If you have an idea, it would help a lot!

**Comment by vanitas92** [comment]
Hi @zhangfuli ,

Please open new issue if you have different request not related from original poster in an already closed issue, otherwise it makes it difficult to track issue requests.

As per your request, this could be due to two possibilities, either the External builder was not correctly mounted on the peer (make sure you have the configmap from the `builders-config.yaml` file in org1 folder applied) or the External Builder did not detect the external value in the metadata.json file and fellback to original Docker building implementation, which is intentionally avoided in this project.

For the first possibility, if you have been following the tutorial i highly doubt it is the issue since the configmap needs to be deployed previously the deployment of the peer, which in case of absence of it, the peer would not be able to start.

For the second possibility, make sure you had packaged correctly the chaincode format as explained in the tutorial, otherwise the external builder would not be able to detect it and install it as external chaincode. Check the logs of the peer (`kubectl logs peer_pod_name -n hyperledger | grep external`) and see what message outputs the external builder after executing the install command.

**Comment by zhangfuli** [comment]
@vanitas92 Thank you for your reply
I have found the problem that these 3 scripts have no execution permissions in the buildpack/bin folder.

**Comment by vanitas92** [comment]
I will close this issue due to it seems to be resolved now and inactivity.
