### ISSUE TITLE
I got an error when I installed chaincode

### ISSUE THREAD

**Issue by jalins** [vanitas92/fabric-external-chaincodes#4]
when I execute the command: `peer lifecycle chaincode install marbles-org1.tgz`, the following error has occurred:
`Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
`
Can you help me with this? I'd appreciate it.

**Comment by vanitas92** [comment]
Hi @Jalins ,

For the error you are mentioning, other people have came with the same problem and i would suggest you make sure that these 3 scripts have execution permissions in the buildpack/bin folder. The scripts are executed in the peer pod as root so changing to 744 permission should be enough. Failing to do so will cause the externalbuilder to fail its execution.

If that does not work either, make sure you had packaged correctly the chaincode format as explained in the tutorial, otherwise the external builder would not be able to detect it and install it as external chaincode. Check the logs of the peer (`kubectl logs peer_pod_name -n hyperledger | grep external`) and see what message outputs the external builder after executing the install command.

Since many people are experiencing the same issue, I will try to improve the scripts and include them in a configmap to be pulled from kubernetes and put them in the peer pods.

**Comment by jalins** [comment]
> Hi @Jalins ,
> 
> For the error you are mentioning, other people have came with the same problem and i would suggest you make sure that these 3 scripts have execution permissions in the buildpack/bin folder. The scripts are executed in the peer pod as root so changing to 744 permission should be enough. Failing to do so will cause the externalbuilder to fail its execution.
> 
> If that does not work either, make sure you had packaged correctly the chaincode format as explained in the tutorial, otherwise the external builder would not be able to detect it and install it as external chaincode. Check the logs of the peer (kubectl logs peer_pod_name -n hyperledger | grep external) and see what message outputs the external builder after executing the install command.
> 
> Since many people are experiencing the same issue, I will try to improve the scripts and include them in a configmap to be pulled from kubernetes and put them in the peer pods.

Thanks for the reply, I'll try it out as you suggested.

**Comment by lc32781971** [comment]
I'm facing the same issue , i checked the permission ,it's permitted enough and the logs don't show anything related to "external" ... 
I think i'm following the correct commands in the tutorial like bellow.
    tar cfz code.tar.gz connection.json
    tar cfz marbles-org1.tgz code.tar.gz metadata.json
    peer lifecycle chaincode install marbles-org1.tgz
i have no idea how to fix this. - -#
could you please have a quick check for this ? 
Thanks.

**Comment by lc32781971** [comment]
> I'm facing the same issue , i checked the permission ,it's permitted enough and the logs don't show anything related to "external" ...
> I think i'm following the correct commands in the tutorial like bellow.
> tar cfz code.tar.gz connection.json
> tar cfz marbles-org1.tgz code.tar.gz metadata.json
> peer lifecycle chaincode install marbles-org1.tgz
> i have no idea how to fix this. - -#
> could you please have a quick check for this ?
> Thanks.

I fixed this by adding this env   CORE_VM_ENDPOINT= unix:///host/var/run/docker.sock
But another issue was raised when approving the chaincode on cli container.

peer lifecycle chaincode approveformyorg --channelID mychannel --name marbles --version 1.0 --init-required --package-id marbles:aeaa62689615ce1114e911868eee80c8477c1e767d182b340565006cc2e4eff9 --sequence 1 -o orderer0:7050 --tls --cafile $ORDERER_CA

Error: failed to endorse proposal: rpc error: code = Unknown desc = error validating proposal: access denied: channel [mychannel] creator org [org1MSP]

**Comment by vanitas92** [comment]
Hi @lc32781971 ,

I noticed that the logging specification is set to `INFO` through the environment variable `FABRIC_LOGGING_SPEC` in the deployment yaml of peers. Can you change the value to `DEBUG` and repeat the process and comeback with the logs as suggested before?

Beware of the huge amount of logs that are going to appear, so that is why i suggested filtering thrrough the word external, on the assumption if the DEBUG level of logging was set, which this level of logs do not appear on INFO.

**Comment by jalins** [comment]
@lc32781971 

`rm -rf   code.tar.gz  marbles-org1.tgz`. Check the scripts 744 permission should be enough, and then `tar cfz code.tar.gz connection.json`, `tar cfz marbles-org1.tgz code.tar.gz metadata.json`.  That's how my problem was solved.

**Comment by lc32781971** [comment]
/opt/gopath/src/github.com/marbles/packaging # peer lifecycle chaincode install marbles-org1.tgz
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint
/opt/gopath/src/github.com/marbles/packaging # ls -lat
total 24
drwxrwxrwx    2 root     root          4096 May 19 13:49 .
-rwxrwxrwx    1 root     root           493 May 19 13:49 marbles-org1.tgz
-rwxrwxrwx    1 root     root           282 May 19 13:48 code.tar.gz
drwxrwxrwx    4 root     root          4096 May 19 13:37 ..
-rwxrwxrwx    1 root     root           399 May 19 12:59 connection.json
-rwxrwxrwx    1 root     root            49 May 19 12:59 metadata.json
/opt/gopath/src/github.com/marbles/packaging # peer lifecycle chaincode install marbles-org1.tgz
Error: chaincode install failed with status: 500 - failed to invoke backing implementation of 'InstallChaincode': could not build chaincode: docker build failed: docker image inspection failed: cannot connect to Docker endpoint

**Comment by vanitas92** [comment]
@lc32781971 

Please execute the chmod 744 to the folder where the `buildpack/bin` scripts are located in your local machine, from picture above seems you have done 777 on the chaincode packaging folder which is not needed. Please also come with the logs suggested after change on FABRIC_LOGGING_SPEC as pointed in previous comment so I can help you further, otherwise it is difficult to help you!

Thanks!

**Comment by lc32781971** [comment]
@vanitas92  
Hi, Thanks for your suggestion and i do find the error logs like bellow by changing the log level to DEBUG .

[36m2020-05-20 10:37:45.766 UTC [chaincode.externalbuilder] Detect -> DEBU 4ea[0m builder 'external-builder' **detect failed: fork/exec /builders/external/bin/detect: no such file or directory**
[36m2020-05-20 10:37:45.766 UTC [chaincode.externalbuilder] Build -> DEBU 4eb[0m no external builder detected for marbles:2466b4c7f04ff7dc2ee841133910587186e6a72a3071c9fe75c87e19ea3a445a

I'm using a kubernetes cluster with 2 worker nodes in my local VM , i'm not sure whether it's caused by my env.
I ls the file in peer node and it's really there.  Is there anything i missed ? 
Thanks a lot.
/opt/gopath/src/github.com/hyperledger/fabric/peer # ls -lat /builders/external/bin/
total 20
drwxr--r--    2 root     root          4096 May 20 03:52 .
drwxr--r--    3 root     root          4096 May 20 03:52 ..
-rwxr--r--    1 root     root          1358 May 20 02:40 build
-rwxr--r--    1 root     root          1127 May 20 02:40 detect
-rwxr--r--    1 root     root          1247 May 20 02:40 release
/opt/gopath/src/github.com/hyperledger/fabric/peer #

**Comment by vanitas92** [comment]
Hi @lc32781971 ,

It migh be related to your setup. A bit concerned about the two worker nodes in your local VM. The approach on having a volume attached to a hostpath was taken in the hopes of a development environment, very easy kubernetes setup just to play with it. For your environment, you have to make sure that both worker nodes point at the same hostpath of the VM at the same time, as hostpath is just intended for a single worker nodes deployment.

Another approach i would take is to mount the scripts through a configmap and then you will have them available in whatever node you deploy if you use that kind of setups. My plan is to update as soon as i have a bit more time on that, but you can try it and see if it works for you.

**Comment by vanitas92** [comment]
Hi @lc32781971 ,

Have you fixed the issue? I have now included the buildpack scripts as configmap and ensure enough permissions on the file to make sure all peer pods execute the externalbuilders correctly. Can you give it a try and see if it works for you?

**Comment by vanitas92** [comment]
Closing this issue since no response back for 10 days
